const q2 = [
    ["There are no carp that aren't fish","c"  ],
    ["There are no fish that aren't cod","d"  ],
    ["Some haddock are plants","e"  ],
    ["Some piranhas are fish","a"  ],
    ["Some fish are sharks","b"  ],
    ["There are no salmon that aren't fish","c"  ],
    ["There are no fish that aren't tuna","d"  ],
    ["Some trout are shellfish","e"  ],
    ["Some alligators are reptiles","a"  ],
    ["Some reptiles are crocodiles","b"  ],
    ["There are no geckos that aren't reptiles","c"  ],
    ["There are no reptiles that aren't iguanas","d"  ],
    ["Some lizards are amphibians","e"  ],
    ["Some salamanders are reptiles","a"  ],
    ["Some reptiles are snakes","b"  ],
    ["There are no tortoises that aren't reptiles","c"  ],
    ["There are no reptiles that aren't newts","d"  ],
    ["Some eagles are fungi","e"  ],
    ["Some canaries are birds","a"  ],
    ["Some birds are crows","b"  ],
    ["There are no owls that aren't birds","c"  ],
    ["There are no birds that aren't sparrows","d"  ],
    ["Some peacocks are bacteria","e"  ],
    ["Some parrots are birds","a"  ],
    ["Some birds are pigeons","b"  ],
    ["There are no vultures that aren't birds","c"  ],
    ["There are no mammals that aren't cats","d"  ],
    ["Some horses are plants","e"  ],
    ["Some dogs are mammals","a"  ],
    ["Some mammals are pigs","b"  ],
    ["There are no elephants that aren't mammals","c"  ],
    ["There are no mammals that aren't sheep","d"  ],
    ["Some bears are shellfish","e"  ],
    ["Some monkeys are mammals","a"  ],
    ["Some mammals are cows","b"  ],
    ["There are no wasps that aren't insects","c"  ],
    ["There are no insects that aren't spiders","d"  ],
    ["Some cockroaches are amphibians","e"  ],
    ["Some caterpillars are insects","a"  ],
    ["Some insects are ant","b"  ],
    ["There are no flies that aren't insects","c"  ],
    ["There are no insects that aren't mosquitoes","d"  ],
    ["Some butterflies are fungi","e"  ],
    ["Some beetles are insects","a"  ]
  ]

  export default q2