const q5 = [
  ["Some carp are fish","a"  ],
  ["Some fish are cod","b"  ],
  ["There are no haddock that aren't fish","c"  ],
  ["There are no fish that aren't piranhas","d"  ],
  ["Some sharks are shellfish","e"  ],
  ["Some salmon are fish","a"  ],
  ["Some fish are tuna","b"  ],
  ["There are no trout that aren't fish","c"  ],
  ["There are no reptiles that aren't alligators","d"  ],
  ["Some crocodiles are amphibians","e"  ],
  ["Some geckos are reptiles","a"  ],
  ["Some reptiles are iguanas","b"  ],
  ["There are no lizards that aren't reptiles","c"  ],
  ["There are no reptiles that aren't salamanders","d"  ],
  ["Some snakes are fungi","e"  ],
  ["Some tortoises are reptiles","a"  ],
  ["Some reptiles are newts","b"  ],
  ["There are no eagles that aren't birds","c"  ],
  ["There are no birds that aren't canaries","d"  ],
  ["Some crows are bacteria","e"  ],
  ["Some owls are birds","a"  ],
  ["Some birds are sparrows","b"  ],
  ["There are no peacocks that aren't birds","c"  ],
  ["There are no birds that aren't parrots","d"  ],
  ["Some pigeons are plants","e"  ],
  ["Some vultures are birds","a"  ],
  ["Some mammals are cats","b"  ],
  ["There are no horses that aren't mammals","c"  ],
  ["There are no mammals that aren't dogs","d"  ],
  ["Some pigs are shellfish","e"  ],
  ["Some elephants are mammals","a"  ],
  ["Some mammals are sheep","b"  ],
  ["There are no bears that aren't mammals","c"  ],
  ["There are no mammals that aren't monkeys","d"  ],
  ["Some cows are amphibians","e"  ],
  ["Some wasps are insects","a"  ],
  ["Some insects are spiders","b"  ],
  ["There are no cockroaches that aren't insects","c"  ],
  ["There are no insects that aren't caterpillars","d"  ],
  ["Some ant are fungi","e"  ],
  ["Some flies are insects","a"  ],
  ["Some insects are mosquitoes","b"  ],
  ["There are no butterflies that aren't insects","c"  ],
  ["There are no insects that aren't beetles","d"  ]
]
export default q5