const q4 = [
  ["Some carp are plants","e"  ],
  ["Some cod are fish","a"  ],
  ["Some fish are haddock","b"  ],
  ["There are no piranhas that aren't fish","c"  ],
  ["There are no fish that aren't sharks","d"  ],
  ["Some salmon are shellfish","e"  ],
  ["Some tuna are fish","a"  ],
  ["Some fish are trout","b"  ],
  ["There are no alligators that aren't reptiles","c"  ],
  ["There are no reptiles that aren't crocodiles","d"  ],
  ["Some geckos are amphibians","e"  ],
  ["Some iguanas are reptiles","a"  ],
  ["Some reptiles are lizards","b"  ],
  ["There are no salamanders that aren't reptiles","c"  ],
  ["There are no reptiles that aren't snakes","d"  ],
  ["Some tortoises are fungi","e"  ],
  ["Some newts are reptiles","a"  ],
  ["Some birds are eagles","b"  ],
  ["There are no canaries that aren't birds","c"  ],
  ["There are no birds that aren't crows","d"  ],
  ["Some owls are bacteria","e"  ],
  ["Some sparrows are birds","a"  ],
  ["Some birds are peacocks","b"  ],
  ["There are no parrots that aren't birds","c"  ],
  ["There are no birds that aren't pigeons","d"  ],
  ["Some vultures are plants","e"  ],
  ["Some cats are mammals","a"  ],
  ["Some mammals are horses","b"  ],
  ["There are no dogs that aren't mammals","c"  ],
  ["There are no mammals that aren't pigs","d"  ],
  ["Some elephants are shellfish","e"  ],
  ["Some sheep are mammals","a"  ],
  ["Some mammals are bears","b"  ],
  ["There are no monkeys that aren't mammals","c"  ],
  ["There are no mammals that aren't cows","d"  ],
  ["Some wasps are amphibians","e"  ],
  ["Some spiders are insects","a"  ],
  ["Some insects are cockroaches","b"  ],
  ["There are no caterpillars that aren't insects","c"  ],
  ["There are no insects that aren't ant","d"  ],
  ["Some flies are fungi","e"  ],
  ["Some mosquitoes are insects","a"  ],
  ["Some insects are butterflies","b"  ],
  ["There are no beetles that aren't insects","c"  ]
]

export default q4