const q3 = [
    ["There are no fish that aren't carp","d"  ],
    ["Some cod are plants","e"  ],
    ["Some haddock are fish","a"  ],
    ["Some fish are piranhas","b"  ],
    ["There are no sharks that aren't fish","c"  ],
    ["There are no fish that aren't salmon","d"  ],
    ["Some tuna are shellfish","e"  ],
    ["Some trout are fish","a"  ],
    ["Some reptiles are alligators","b"  ],
    ["There are no crocodiles that aren't reptiles","c"  ],
    ["There are no reptiles that aren't geckos","d"  ],
    ["Some iguanas are amphibians","e"  ],
    ["Some lizards are reptiles","a"  ],
    ["Some reptiles are salamanders","b"  ],
    ["There are no snakes that aren't reptiles","c"  ],
    ["There are no reptiles that aren't tortoises","d"  ],
    ["Some newts are fungi","e"  ],
    ["Some eagles are birds","a"  ],
    ["Some birds are canaries","b"  ],
    ["There are no crows that aren't birds","c"  ],
    ["There are no birds that aren't owls","d"  ],
    ["Some sparrows are bacteria","e"  ],
    ["Some peacocks are birds","a"  ],
    ["Some birds are parrots","b"  ],
    ["There are no pigeons that aren't birds","c"  ],
    ["There are no birds that aren't vultures","d"  ],
    ["Some cats are plants","e"  ],
    ["Some horses are mammals","a"  ],
    ["Some mammals are dogs","b"  ],
    ["There are no pigs that aren't mammals","c"  ],
    ["There are no mammals that aren't elephants","d"  ],
    ["Some sheep are shellfish","e"  ],
    ["Some bears are mammals","a"  ],
    ["Some mammals are monkeys","b"  ],
    ["There are no cows that aren't mammals","c"  ],
    ["There are no insects that aren't wasps","d"  ],
    ["Some spiders are amphibians","e"  ],
    ["Some cockroaches are insects","a"  ],
    ["Some insects are caterpillars","b"  ],
    ["There are no ant that aren't insects","c"  ],
    ["There are no insects that aren't flies","d"  ],
    ["Some mosquitoes are fungi","e"  ],
    ["Some butterflies are insects","a"  ],
    ["Some insects are beetles","b"  ]
  ]

export default q3