const q1 = [
  ["Some anchovies are fish","a"  ],
  ["Some fish are carp","b"  ],
  ["There are no cod that aren't fish","c"  ],
  ["There are no fish that aren't haddock","d"  ],
  ["Some piranhas are plants","e"  ],
  ["Some sharks are fish","a"  ],
  ["Some fish are salmon","b"  ],
  ["There are no tuna that aren't fish","c"  ],
  ["There are no fish that aren't trout","d"  ],
  ["Some alligators are shellfish","e"  ],
  ["Some crocodiles are reptiles","a"  ],
  ["Some reptiles are geckos","b"  ],
  ["There are no iguanas that aren't reptiles","c"  ],
  ["There are no reptiles that aren't lizards","d"  ],
  ["Some salamanders are amphibians","e"  ],
  ["Some snakes are reptiles","a"  ],
  ["Some reptiles are tortoises","b"  ],
  ["There are no newts that aren't reptiles","c"  ],
  ["There are no birds that aren't eagles","d"  ],
  ["Some canaries are fungi","e"  ],
  ["Some crows are birds","a"  ],
  ["Some birds are owls","b"  ],
  ["There are no sparrows that aren't birds","c"  ],
  ["There are no birds that aren't peacocks","d"  ],
  ["Some parrots are bacteria","e"  ],
  ["Some pigeons are birds","a"  ],
  ["Some birds are vultures","b"  ],
  ["There are no cats that aren't mammals","c"  ],
  ["There are no mammals that aren't horses","d"  ],
  ["Some dogs are plants","e"  ],
  ["Some pigs are mammals","a"  ],
  ["Some mammals are elephants","b"  ],
  ["There are no sheep that aren't mammals","c"  ],
  ["There are no mammals that aren't bears","d"  ],
  ["Some monkeys are shellfish","e"  ],
  ["Some cows are mammals","a"  ],
  ["Some insects are wasps","b"  ],
  ["There are no spiders that aren't insects","c"  ],
  ["There are no insects that aren't cockroaches","d"  ],
  ["Some caterpillars are amphibians","e"  ],
  ["Some ant are insects","a"  ],
  ["Some insects are flies","b"  ],
  ["There are no mosquitoes that aren't insects","c"  ],
  ["There are no insects that aren't butterflies","d"  ],
  ["Some beetles are fungi","e"  ]
]

export default q1