const questions = [
    ["Some cod are fish","a"],
    ["Some reptiles are crocodiles","b"],
    ["There are no birds that aren't eagles","e"],
    ["There are no reptiles that aren't alligators","e"],
    ["There are no birds that aren't owls","e"],
    ["Some birds are plants","c"],
    ["There are no cod that aren't fish","d"],
    ["There are no fish that aren't piranhas","e"],
    ["Some reptiles are iguanas","b"],
    ["Some alligators are reptiles","a"],
    ["Some fish are insects","c"],
    ["Some iguanas are reptiles","a"],
    ["There are no fish that aren't cod","e"],
    ["Some birds are crows","b"],
    ["There are no eagles that aren't birds","d"],
    ["Some piranhas are fish","a"],
    ["Some frogs are reptiles","a"],
    ["Some fish are cod","b"],
    ["There are no reptiles that aren't crocodiles","e"],
    ["Some birds are owls","b"],
    ["Some reptiles are insects","c"],
    ["Some fish are shellfish","c"],
    ["Some reptiles are plants","c"],
    ["There are no reptiles that aren't iguanas","e"],
    ["There are no carp that aren't fish","d"],
    ["Some birds are canaries","b"],
    ["There are no piranhas that aren't fish","d"],
    ["Some fish are anchovies","b"],
    ["Some carp are fish","a"],
    ["Some crocodiles are reptiles","a"],
    ["Some fish are mammals","c"],
    ["There are no frogs that aren't reptiles","d"],
    ["Some birds are eagles","b"],
    ["Some eagles are birds","a"],
    ["Some reptiles are mammals","c"],
    ["Some birds are insects","c"],
    ["Some crows are birds","a"],
    ["Some birds are shellfish","c"],
    ["There are no crocodiles that aren't reptiles","d"],
    ["There are no birds that aren't canaries","e"],
    ["There are no fish that aren't carp","e"],
    ["There are no owls that aren't birds","d"],
    ["There are no reptiles that aren't frogs","e"],
    ["There are no alligators that aren't reptiles","d"],
    ["Some fish are carp","b"],
    ["Some fish are plants","c"],
    ["Some reptiles are frogs","b"],
    ["Some anchovies are fish","a"],
    ["Some owls are birds","a"],
    ["There are no anchovies that aren't fish","d"],
    ["Some canaries are birds","a"],
    ["There are no birds that aren't crows","e"],
    ["There are no fish that aren't anchovies","e"],
    ["Some reptiles are shellfish","c"],
    ["Some reptiles are alligators","b"],
    ["There are no canaries that aren't birds","d"],
    ["Some fish are piranhas","b"],
    ["Some birds are mammals","c"],
    ["There are no iguanas that aren't reptiles","d"],
    ["There are no crows that aren't birds","d"]
]
export default questions